spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: secret
  flyway:
    enabled: true
    locations: classpath:db/migration
  application:
    name: ChordsAndTabs
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 0205ef150346f2
    password: 250cb5ade767a2
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

