spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:mydatabase}
    username: ${DB_USER:myuser}
    password: ${DB_PASSWORD:secret}
  flyway:
    enabled: true
    locations: classpath:db/migration
  application:
    name: ChordsAndTabs
  mail:
    host: ${MAIL_HOST:sandbox.smtp.mailtrap.io}
    port: ${MAIL_PORT:2525}
    username: ${MAIL_USER:api}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

app:
  jwt:
    secret: ${JWT_SECRET:secret}

